# Goal
std_msgs/Bool get_torso_point
std_msgs/Bool get_drawn
sensor_msgs/Image image
---
# Result
std_msgs/Bool success
geometry_msgs/PointStamped point
sensor_msgs/Image skeleton_img
utbots_msgs/Skeleton2d skeleton_points_normalized
---
# Feedback