# Goal
std_msgs/String[] target_categories
std_msgs/Int32 batch_size
std_msgs/Float32 iou_threshold
std_msgs/Float32 support_threshold
---
# Result
utbots_msgs/BoundingBoxes detected_objs
sensor_msgs/Image annotated_image
---
# Feedback
